version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: shopping_cart_zookeper
    ports:
      - "2181:2181"
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: shopping_cart_kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
#      SERVER_SERVLET_CONTEXTPATH: "/"
#      SERVER_PORT: "9801"
    depends_on:
      - "kafka"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: shopping_cart_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  postgres:
    image: postgres:latest
    container_name: shopping_cart_postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=shopping_cart"
      - "POSTGRES_PASSWORD=shopping_cart"
    ports:
      - "5432:5432"  # credentials (shopping_cart:shopping_cart)
